
[paths]
db_path = "/Users/brett/Documents/LOC-02/locness_post_res.db"
parquet_path = "loc02_uw_qc.parquet"
csv_path = "loc02_uw_qc.csv"

[calibration]
# pH calibration coefficients
# mFET005 SB10 (old, used during LOC-02)
# ph_k0 = -1.39469
# ph_k2 = -0.00107

# mFET005 SB10 (from Joe Warren's email 2025-07-29, used for post-processing)
ph_k0 = -1.3944286
ph_k2 = -0.0010700

[resample]
resample_interval = "2s"
